## Author: Francisco Carrillo-Perez

# 1. Tensors and using the GPU

In this notebook we are going to:
  - Introduce what tensors are.
  - Explain the main characteristics of Pytorch.
  - Usage of GPU in Pytorch
  

## 1.1 Tensors

Tensors are the atoms of Deep Learning. If you are familiar with Python libraries for working with data, they are numpy arrays. Specifically, they are multi-dimensional matrixes containing elements of a single data type. With them we can perform any type of operation.

In [1]:
# Importing mandatory libraries
%matplotlib inline
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision

import numpy as np
from IPython.core.debugger import set_trace

In [2]:
# Numpy eye return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [3]:
# Torch eye returns exactly the same
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [4]:
# numpy
np.random.random((5, 3))

array([[0.2558086 , 0.74128062, 0.25965641],
       [0.09936786, 0.1673001 , 0.55690701],
       [0.2664226 , 0.48058196, 0.82787683],
       [0.72053646, 0.6029763 , 0.55256614],
       [0.22927234, 0.80039224, 0.60043843]])

In [5]:
# torch
torch.rand((5, 3))

tensor([[0.0597, 0.9416, 0.1116],
        [0.9945, 0.4218, 0.4852],
        [0.9088, 0.5455, 0.2470],
        [0.9104, 0.5235, 0.7916],
        [0.6343, 0.3592, 0.6058]])

In [8]:
X = np.random.random((2,2))
Y = np.random.random((2,2))
Z_numpy = X + Y
Z_numpy

array([[1.40672779, 0.71710621],
       [1.29692769, 1.38485705]])

In [9]:
# Summing operations
X = torch.rand((2,2))
Y = torch.rand(2,2)
Z_torch = X + Y
Z_torch

tensor([[0.6548, 1.5534],
        [0.9509, 1.1317]])

In [10]:
# We can perform conversions from tensors to numpy an vice versa
Z_tonumpy = Z_torch.numpy()
print(Z_tonumpy)
Z_totensor = torch.from_numpy(Z_numpy)
print(Z_totensor)

[[0.65484285 1.5533524 ]
 [0.95094985 1.1317469 ]]
tensor([[1.4067, 0.7171],
        [1.2969, 1.3849]], dtype=torch.float64)


## 1.2 GPU

I've heard that Deep Learning needs a ton of computation. How can I use my brand new GPU with Pytorch?

In [11]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

You can move the tensor to the GPU if available as follows:

In [12]:
data = torch.eye(3)
data.to(device)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])